name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Pacman Animation
        uses: aelassas/snk@main
        with:
          github_user_name: yashshinde0080
          outputs: |
            dist/pacman.svg?color_snake=yellow&color_dots=#1e1e2e,#313244,#45475a,#585b70,#cdd6f4
            dist/pacman-dark.svg?color_snake=yellow&palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
